packageExtensions:
  # TODO remove this once pnp supports `imports`
  # https://github.com/yarnpkg/berry/issues/3843#issuecomment-1146568693
  chalk@^5:
    dependencies:
      "#ansi-styles": "npm:ansi-styles@^6"
      "#supports-color": "npm:supports-color@^9"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.6.1.cjs
