packageExtensions:
  # TODO remove this once pnp supports `imports`
  # https://github.com/yarnpkg/berry/issues/3843#issuecomment-1146568693
  chalk@^5:
    dependencies:
      "#ansi-styles": "npm:ansi-styles@^6"
      "#supports-color": "npm:supports-color@^9"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
